18.6. Код-ревью домашнего задания
Serg-E-DEV/Exercises-PS-HTML-CSS pull request #3
Opened 2024-01-23 16:47 UTC by Serg-E-DEV

Алексей, добрый вечер! Задания выполнены ) Появился какой-то странный merge в ветке, я не понимаю, откуда он взялся.

2024-01-24 08:04 UTC, GitEsense requested changes
В целом всё хорошо, но есть пара замечаний - обрати внимание)

2024-01-24 08:04 UTC, GitEsense commented on 2-Form/styles/style.css
декорацию надобно бы убрать

2024-01-24 08:04 UTC, GitEsense commented on 2-Form/styles/style.css
>  	line-height: 19px;
а где color? )

2024-01-24 08:04 UTC, GitEsense commented on 2-Form/styles/style.css
класс 
содержимое div class="form-agree" не идёт в одну линию - надобно бы центрировать по строке, если будет увеличение шрифта, то чекбокс будет прижат к низу строки, а это было бы не совсем корректно

2024-01-24 16:30 UTC, Serg-E-DEV commented on 1-Blog/index.html
>  		</form>
Понял ) Да, нажал, отправляет на другую страницу. Исправлю.

2024-01-24 17:24 UTC, Serg-E-DEV commented on 1-Blog/index.html
> +			<div>Мой блог</div>
Согласен. Попробовал стилизовать его полностью.

`
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,700,700i&display=swap">
	<title>TEST Logo</title>
	<style>
		body {
			height: 100vh;
			padding: 100px;

			background: linear-gradient(180deg, #374151 0%, #111827 100%);

			font-family: 'Roboto', sans-serif;
			font-size: 16px;
			font-weight: 400;
			line-height: 1.2em;
			color: #fff;
		}

		a {
			color: #fff;
			text-decoration: none;
		}

		.logo {
			display: flex;
			flex-flow: row nowrap;
			gap: 11px;
			align-items: center;
		}

		.logo__img {
			width: 35px;
			height: 35px;

			background-color: #4b5563;
			border-radius: 4px;
			box-shadow: 0px 15px 30px 0px #00000026;

			font-family: 'Source Sans Pro', sans-serif;
			font-size: 18px;
			font-weight: 600;
			line-height: 35px;
			color: #fff;
			text-align: center;
		}

		.logo__name {
			font-size: 18px;
			font-weight: 400;
			line-height: 35px;
		}
	</style>
</head>
<body>
	<a class="logo" href="#">
		<div class="logo__img">B</div>
		<div class="logo__name">Мой блог</div>
	</a>
</body>
</html>
`

2024-01-24 17:31 UTC, Serg-E-DEV commented on 1-Blog/index.html
> +			<div>Мой блог</div>
Код отправил через платформу https://app.purpleschool.ru/courses/12/sections/187/lessons/1362
А как код отправить, если вдруг вопрос?

2024-01-24 17:34 UTC, GitEsense commented
Сделай изменения коммитом, ибо читать в комментариях к дз - это нереально)
Жду )

2024-01-24 17:36 UTC, GitEsense commented on 1-Blog/index.html
> +			<div>Мой блог</div>
Пиши в телеграмм боте через призыв ментора

2024-01-24 17:39 UTC, Serg-E-DEV commented on 1-Blog/index.html
> +			<div>Мой блог</div>
Я в коммит залил пример. Так можно?

2024-01-24 17:57 UTC, GitEsense commented on 1-Blog/index.html
> +			<div>Мой блог</div>
Можно, но лучше "в реальном времени" диалог вести, гит для примеров кода будет не лучшим вариантом, ты можешь через github pages показать ветку и там сделать блок с примером кода, но лучше в телеге реалтайм

2024-01-24 18:35 UTC, Serg-E-DEV commented on 2-Form/styles/style.css
Подчёркивание у нижней ссылки в форме убрал. Центровку чекбокса и метки сделал.

2024-01-24 18:40 UTC, Serg-E-DEV commented on 2-Form/styles/style.css
>  	line-height: 19px;
color для метки задал, но он так же задан в body. Я правильно понял?

2024-01-24 18:44 UTC, Serg-E-DEV commented
Изменения внёс

2024-01-25 08:40 UTC, GitEsense approved these changes

2024-01-25 08:40 UTC, GitEsense commented on 1-Blog/logo.html
> +</body>
А как тебе такой вариант?)

```
<a id="link-home" href="#">
  <div class="logo">
    <span class="logo__img">B</span> Мой Блог
  </div>
</a>
```

И классы:
```
* {
  box-sizing: border-box;
}
body {
  background: #000;
}
#link-home {
  color: #fff;
  font-size: 16px;
  font-weight: 400;
  text-decoration: none;
}
.logo {
  font-size: 18px;
}
.logo__img {
  border-radius: 3px;
  background: #4b5563;
  padding: 8px 12px;
  box-shadow: 0px 15px 30px 0px rgba(0, 0, 0, 0.15);
}
```

2024-01-25 14:49 UTC, Serg-E-DEV commented on 1-Blog/index.html
> +			<div>Мой блог</div>
С иконкой всё ок?

2024-01-25 14:50 UTC, Serg-E-DEV commented on 2-Form/styles/style.css
>  	line-height: 19px;
Вы не ответили )

2024-01-25 14:54 UTC, Serg-E-DEV commented on 2-Form/styles/style.css
>  }
Да, я так делал, но столкнулся с другой проблемой - при увеличении шрифта или сжатии границ лейбл разбивается на две строки, и чекбокс выравнивается по вертикали посередине двух строк, что смотрится не очень. Решение, которое я использовал, вроде бы работает и с большим шрифтом и с двумя строками нормально.

2024-01-25 15:07 UTC, GitEsense commented on 1-Blog/index.html
> +			<div>Мой блог</div>
Да, с лого всё окей)

2024-01-25 15:09 UTC, Serg-E-DEV commented on 1-Blog/logo.html
> +</body>
Мне нравится. Я поэкспериментировал с этим. А чем этот подход выигрышнее? Меньше стилей?

2024-01-25 15:22 UTC, GitEsense commented on 2-Form/styles/style.css
>  }
Имеет право на жизнь, но vertical-align сделает одно и то же, вопрос лишь в поведении флекса, тут нужно было бы просто его доработать

2024-01-25 15:26 UTC, Serg-E-DEV commented on 2-Form/styles/style.css
>  	line-height: 19px;
Понял )

2024-01-25 15:27 UTC, Serg-E-DEV commented on 1-Blog/logo.html
> +</body>
Смотрится изящно, но я не могу понять почему ))

2024-01-25 15:31 UTC, Serg-E-DEV commented on 2-Form/styles/style.css
>  }
А как? Я пробовал по-разному это сделать, но не нашёл решения оптимального.

2024-01-25 16:32 UTC, GitEsense commented on 1-Blog/logo.html
> +</body>
Во-первых, тут минимум блочных элементов, т.е. всё в одной обёртке(которой можно было и не делать, а сделать саму ссылку блочной), т.е. даже див можно было бы выкинуть, во-вторых, по стилям link-home мог бы вообще иметь только font-size , т.к. мы бы для nav a задали стили ссылок (цвет, декорации, font-weight и т.п.), получается переиспользование стилей, следовательно меньше дублирования кода, сам же logo__img будет иметь форму квадрата по заливке при любом размере шрифта, если заменить padding на 0.3em 0.6em

2024-01-25 17:09 UTC, Serg-E-DEV commented on 1-Blog/logo.html
> +</body>
Да, теперь понял. Я залил в коммит исправленный вариант. Убрал всё кроме a и span. Мне нравится такой вариант )))

2024-01-26 01:07 UTC, Serg-E-DEV commented on 2-Form/styles/style.css
>  }
Я доработал выравнивание через flex на основе вашего примера. У меня появилась такая идея. В качестве базы задал шрифт у .form-agree, а затем привязался к нему так, чтобы при изменении размера шрифта - чек бокс и лейбл увеличивались пропорционально и оставались на одном уровне. Что скажете? Залил в коммит.

2024-01-26 11:44 UTC, GitEsense approved these changes
Можешь мерджить и идти дальше)
По HTML вопросов нет, по CSS вариантов решение много, но дальше будет речь о методологиях и принципах, там уже будем их соблюдать)

2024-01-26 11:44 UTC, GitEsense commented on 2-Form/styles/style.css
>  }
Выглядит интересно и масштабируется, в данном случае излишне, но сама идея интересна

2024-01-26 11:51 UTC, merged